### ISSUE TITLE
Unable to execute in Windows 10 (PATH)

### ISSUE THREAD

**Issue by harshakumar347** [Owez/yark#128]
![image](https://github.com/Owez/yark/assets/25246216/5156978e-3753-4d7c-8ba1-d9b9f52d920a)

I am using windows 10 . I installed yark using pip3 install yark command it executed successfully . but unable to execute yark

**Comment by Owez** [comment]
Hi, it should've been added to PATH so you can execute it manually. If you're not too bothered about fixing this, just run the following to use Yark instead:

```
pip3 -m yark
```

But if you want to fix it there's some more manual steps you have to do; these may not be completely right but it should help you to figure out the issue on your own: 

1. `pip show yark`: Find the install location of Yark
2. Go into your file explorer to around abouts where it says and copy the path to it
3. Open the [PATH editor](https://www.computerhope.com/issues/ch000549.htm) for Windows 10
4. Paste in the path you copied in step 2 and save
5. Restart your computer
