### ISSUE TITLE
Handling deleted videos

### ISSUE THREAD

**Issue by GuillaumeRoss** [Owez/yark#132]
Hi!

I did look at the documentation, apologies if this is documented somewhere I missed, but I think there are probably feature requests in what I'm about to discuss anyway.

How does yark handle video removal from a channel or playlist? There are channels I archive with yark for which I absolutely do NOT want to remove videos, ever. I have extra backups so I know at least the actual video files are safe, but it would be nice to have a "no delete" option - maybe that would mark the videos as having been deleted when serving the site, but leaving them there.

**Comment by Owez** [comment]
Hey, no problem. The docs are quite sparse to be fair – I should probably add an in-depth algorithm explainer.

Every time Yark runs it'll get all channel information (e.g. all videos), and then it will download the videos present. It then checks the channel informartion against the information in the archive, and add/update the archive with the new information. Including the _lack_ of a video via the `deleted` tag.

For example, if Video A was archived, then the uploader deletes the video, and the channel was archived again, Yark will tag Video A as `deleted`. The `deleted` tag also tracks if a video is privated, so you have a history of when the uploader privated and unprivated the video. Archives are always additive, they'll never delete information.

I don't think there's a nice UI indicator for it at the moment but it might be in the per-video bulletpoint history. 

---

Overall, Yark will keep and properly archive the deleted/privated state of a video. As long as you keep the archive backed up, you should never lose information :)

**Comment by GuillaumeRoss** [comment]
Awesome, great to hear confirmation that it will not delete anything. 

I added a line in the README in : https://github.com/Owez/yark/pull/133
