### ISSUE TITLE
The message “Video not found” is displayed if there was an error during the download

### ISSUE THREAD

**Issue by ramioimar** [Owez/yark#137]
During download the error was happend 

>  • Unknown error whilst downloading videos, details below:
> ERROR: unable to download video data: HTTP Error 403: Forbidden, retrying in a few seconds..           
>   • Unknown error whilst downloading videos, details below:
> ERROR: unable to download video data: HTTP Error 403: Forbidden                                        
>   • Sorry, failed to download videos
> Please file a bug report if you think this is a problem with Yark!

15 The video was successfully uploaded, but when I try to run `yark view <channel-name>` I only see the screen with following message "No videos found!". 
I expect the uploaded video to be presented. It is available for viewing through the file system.

 Details:
- thumbnails - 47 items
- videos - 16 items 
- yark.json
> version: 3
> url: "<channel link>"
> videos: []
> livestreams: []
> shorts: []

**Comment by Owez** [comment]
Yeah this is an issue with how it's processed, I'll try to put a fix in sometime next week. It saves the metadata only on success right now, so if something makes the application panic it may have downloaded 50 videos but never saved the important metadata
