### ISSUE TITLE
Update yark dependency

### ISSUE THREAD

**Issue by ramioimar** [Owez/yark#138]
I tried to update yt-dlp and received and error

`
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yark 1.2.10 requires yt-dlp==2023.10.13, but you have yt-dlp 2024.10.7 which is incompatible.
`

**Comment by Owez** [comment]
I'll update it now

**Comment by Owez** [comment]
Done, the new version is 1.2.11 :)
