### ISSUE TITLE
Need a bit of help.  how do you specify the format to download?

### ISSUE THREAD

**Issue by kanliot** [Owez/yark#19]
What I want is to use an existing yt-dlp or bash command string to archive the new videos.

I don't see a way to do this. 

I there a way to expose this function? 

Bash would be better, actually, also, it should handle retries. 

Thanks.

**Comment by Owez** [comment]
Yark isn't intended to have that sort of customisability with archiving for now. It selects the best quality video/audio it can find (or failing that, any video selection) – this will be improved with later releases.

Feel free to download/fork the script and change the `yt-dlp` download config which can be found [here](https://github.com/Owez/yark/blob/master/yark.py#L171) as of the time of writing. Yark doesn't use the terminal to invoke `yt-dlp`.

**Comment by kanliot** [comment]
Thanks for the reply.  I agree this issue is closed. 

Since I haven't any familiarity with the code, could you kindly tell me what this app uses to look for new videos?  I expect you use some kind of loop, but how does it know if there is a new video, or how many videos have been added?

**Comment by Owez** [comment]
It uses yt-dlp to get all of the metadata for the videos, then it compares all of the downloaded metadata to the stuff it has on file inside of the `yark.json`. So it knows what information has been added/updated/deleted. Getting the metadata takes ages so I wish there was a better way to do it :)
