### ISSUE TITLE
Native playlist downloading

### ISSUE THREAD

**Issue by ckp95** [Owez/yark#49]
Hey, saw this in Hackernews, looks pretty neat.

Even though the README only mentions channels, I know that yt-dlp also supports downloading playlists. When I give it a playlist that has videos that were deleted, yark breaks. This is common in music playlists, for example [this one](https://www.youtube.com/playlist?list=PLtew1NuUwxVy2ct76AZU6azkuRj8WAn5K). 

I had a quick look in the code, I managed to get it to work with this simple hotfix:

```
diff --git a/yark/channel.py b/yark/channel.py
index 4863823..26eb7af 100644
--- a/yark/channel.py
+++ b/yark/channel.py
@@ -139,6 +139,7 @@ class Channel:
         settings = {
             "outtmpl": "%(id)s%(ext)s",
             "logger": VideoLogger(),
+            "ignoreerrors": True
         }
 
         # Get response and snip it
@@ -188,6 +189,8 @@ class Channel:
                 else:
                     _err_msg(f"Unknown video kind '{kind}' found", True)
 
+        videos = [x for x in videos if x is not None]
+
         # Parse metadata
         self._parse_metadata("video", videos, self.videos)
         self._parse_metadata("livestream", livestreams, self.livestreams)
```

I'm not making a formal PR because you might know of a cleaner way of implementing this check, but you're welcome to apply this patch if you want. Also it might be good to mention in the README that it works on playlists too, not just channels.

**Comment by sw-yx** [comment]
just leaving a +1 for playlist downloading - just to motivate it - i'd like to back up every video i've ever "liked" as a simple way of guarding against bitrot and enabling proper search since youtube search sucks.


thank you for this project @owez and looking forward to v1.3!
