### ISSUE TITLE
Skip pending livestreams when archiving

### ISSUE THREAD

**Issue by ameyoyo** [Owez/yark#60]
Hi again, sorry to open another issue. 

Will you give the option to skip pending livestreams when archiving channels? It would be annoying to often wait for those streams to finish before being able to run yark on a streamer's channel. 

![image](https://user-images.githubusercontent.com/47435073/211063797-df614e02-8af9-4629-b86e-9c9242a07c03.png)

**Comment by Owez** [comment]
No problem at all, open as many as you need :)

Looks like this is an oversight with metadata downloading, I'm suprised yt-dlp gives a fatal error for this instead of just returning a warning and doing nothing. I'll fix it in the 1.2.1 version soon
