### ISSUE TITLE
Error showing Report on Windows 10 x64 - Python 3.9

### ISSUE THREAD

**Issue by Jonatandb** [Owez/yark#61]
As I earlier reported on reddit post, I have this error during execution of refresh command:

![image](https://user-images.githubusercontent.com/8082172/211077875-a4b249ef-d5ae-4037-adbe-85819f1ccf28.png)

Note: This error don't avoid to run and use correctly the "view" command.

The error says:
"UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f50e' in position 42: character maps to _undefined_"

So I have found that character '\U0001f50e' is the maginify icon: 🔎 (https://emojipedia.org/es/emoji/%F0%9F%94%8E/)

I have tried to fix it by looking in the code, but I couldn't find the magnify icon neither the Unicode code: 1f50e  ☹

**Comment by Owez** [comment]
My best guess is that the command prompt has ascii-only support and higher unicode values like the magnify glass break it. I'd reccomend using powershell or the new windows terminal program as a workaround until an ascii-only mode is added

**Comment by Jonatandb** [comment]
Interesting, I will try that! 💪🏻

**Comment by Jonatandb** [comment]
Earlier I was using git-bash.

Now I have this on Windows cmd:
![image](https://user-images.githubusercontent.com/8082172/211088042-cc1550c3-61b3-4973-aa01-5aed62414871.png)

And this on PowerShell:
![image](https://user-images.githubusercontent.com/8082172/211088071-7f1352f5-3e93-423c-982d-d2dcbf351875.png)

At least I have no more errors 😅

**Comment by Owez** [comment]
Aha gotcha, all of my enviroments have full ascii support- I'm suprised powershell doesn't support it. I'll do ascii support eventually, got a lot on my plate in terms of new features for the foreseeable future
