### ISSUE TITLE
How to handle multiple channels?

### ISSUE THREAD

**Issue by gerroon** [Owez/yark#70]
Hi

Am I supposed to create a new archive for each channel? Would refresh remember to download videos from archives?

**Comment by Owez** [comment]
For now the supported way is just to create multiple archives for each channel, there's no multi-archive management build into Yark directly. Best way is just to make a shell/batch file to do refreshes:

```shell
echo "Starting archival.."
yark refresh jimmyhendrix
yark refresh allstar
yark refresh pewdiepie
echo "Archiving finished!"
```

You might also want to add `set -e` at the top so the script errors out if one channel fails
