### ISSUE TITLE
Long-term archival/application changes

### ISSUE THREAD

**Issue by Owez** [Owez/yark#72]
After Yark 1.3 and it's patches it might be worth doing one or more of these possibilities for the future "Yark 1.4" or maybe "Yark 2":

1. **Move the current JSON archives to a better SQLite database** – This would be good because having a proper relational database would allow more complex visualisations and easier expansion of the archives. The negative is that SQLite is hard to read and would need a lot of docs and possible tests
2. **Rewrite the archiver for better readability and to consilidate current features** – This would remove some tech debt which I can see happening on the distant horizon and give the project a chance to do everything right. The negative is that there's a managable amount of tech debt and this might just result in wasted work
3. **Move to Rust** – I'm mainly a Rust developer and though it'll take a while to develop, it would make the archival rock solid and would also allow for a more expansion for the visualiser, also mixing well with option 1. The negative to this is the most radical of the desicions and would mean finding a way to bind with yt-dlp properly (pyo3); it's the high-risk high-reward option

Deciding on if any of these options should go forward; I think 1.3 will give Yark enough features so that slow and steady work can be made on one of these options. Because the archive format is stable, migrating to SQLite is fine and will just involve porting the current JSON data into a nicer SQLite form.

**Comment by Owez** [comment]
Over the course of doing #56 I'm slowly getting more tempted to do option 1 + 3. Half the battle right now is figuring out type issues because mypy isn't exhaustive and a lot get through the cracks. They can be papered over with polish but I'd rather consilidate it into a type-safe system.

**Comment by YummyOreo** [comment]
> 3\. The negative to this is the most radical of the desicions and would mean finding a way to bind with yt-dlp properly (pyo3); it's the high-risk high-reward option

There is a lib in rust to download youtube videos and get info on it. Idk if it uses yt-dlp. Here is the github link: https://github.com/DzenanJupic/rustube

**Comment by Owez** [comment]
Closing this issue for now because I've been slowly upgrading code quality in the library and I think with some more consilidation and effort the current code is more than alright to keep building on. I still like the idea of using SQLite long-term and it makes a lot of sense to use, but JSON shouldn't be an issue until somewhere like Yark 1.6 at this rate. Will reopen if one of these needs to happen.
