### ISSUE TITLE
Can't create an archive for playlists.

### ISSUE THREAD

**Issue by MasaruKitajima** [Owez/yark#90]
I wanted to archive a playlist, [Photoshop Tutorials](https://youtube.com/playlist?list=PLKd2D0wlOFGnNQfY9E4263nATGGgM7vMR). So after installation, I typed in the following commands.

```bash
yark new pixelsurplus
https://www.youtube.com/playlist?list=PLKd2D0wlOFGnNQfY9E4263nATGGgM7vMR
```
then got this,

```bash
zsh: no matches found: https://youtube.com/playlist?list=PLKd2D0wlOFGnNQfY9E4263nATGGgM7vMR
```

How can I archive a playlist?

**Comment by Owez** [comment]
You have to wrap it in `''` quotes like this: `yark new pixelsurplus 'https://www.youtube.com/playlist?list=PLKd2D0wlOFGnNQfY9E4263nATGGgM7vMR'` :)

**Comment by MasaruKitajima** [comment]
@Owez , Thank you for your instructions. But still, I met an error. I posted a new issue as [91](https://github.com/Owez/yark/issues/91)
