### ISSUE TITLE
Migrate code to Python 3.11

### ISSUE THREAD

**Issue by Owez** [Owez/yark#95]
#93 made it so Python 3.11.x is the only valid version for Python, but the actual code of Yark is still 99% Python 3.9 after a few commits. This issues intention is to remove any Python 3.9 code and replace it with new 3.11 features wherever possible. Migrating to dataclasses is also a part of this.

**Comment by bcsamrudh** [comment]
@ Owez , I could help you out with this issue.

**Comment by Owez** [comment]
> @ Owez , I could help you out with this issue.

I'm rewriting Yark in Rust at the moment so the current Python code will be discarded so I'll close this issue. I appreciate the offer to help :)
