### ISSUE TITLE
Better progress indicator for downloading metadata

### ISSUE THREAD

**Issue by finnatsea** [Owez/yark#96]
I am just starting to use yark and I thought I was doing something wrong after the cli seemed to hang on the `Downloading metadata...` step.

I kept restarting the script because I thought my IP was getting blocked or something. I left it running and went to get a coffee and it turned out it was working, I just couldn't see it.

<img width="333" alt="Screenshot 2023-01-20 at 12 37 00 PM" src="https://user-images.githubusercontent.com/43194191/213766695-032a7213-52d4-4ac4-941c-d44b404ad0d1.png">

^some progress indicator here would really help new users.

**Comment by Owez** [comment]
Yep, I think something like why PyPI or Poetry has would be nice. I do sometimes press enter to make sure it didnt freeze when im testing. Should be quite easy to add

**Comment by Owez** [comment]
Closed in #98, if you run `pip3 install yark --upgrade` you should have a nice new loading spinner :)
